name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploying:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: "HRKU-fd8b6546-35c2-4c76-a739-9876aab035d0"
        run: |
          # Authenticate to Heroku
          echo $HEROKU_API_KEY | heroku auth:token
          
          # Verify authentication
          heroku auth:whoami
          
          # Add Heroku remote
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/node-ci-cd.git
          
          # Push to Heroku
          git push heroku main
